### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by cihansakman** [ProgVal/python-powertop#1]
Hi, I'm getting an AssertionError while trying to run the following code snippets....

```
import powertop
import json

measures = powertop.Powertop().get_measures(time=1)

print(json.dumps(measures['Device Power Report'], indent=4))
```

I'm installing the last version of Powertop, *PowerTOP version 2.15*

Here is the detailed Error 

> Cannot load from file /var/cache/powertop/saved_parameters.powertop
File will be loaded after taking minimum number of measurement(s) with battery only 
Cannot load from file /var/cache/powertop/saved_parameters.powertop
File will be loaded after taking minimum number of measurement(s) with battery only 
Traceback (most recent call last):
  File "/home/manjaro/Projects/Dark Energy/example2.py", line 65, in <module>
    measures = powertop.Powertop().get_measures(time=1)
  File "/home/manjaro/anaconda3/lib/python3.9/site-packages/powertop/decoder.py", line 26, in get_measures
    return self._parse_output(output)
  File "/home/manjaro/anaconda3/lib/python3.9/site-packages/powertop/decoder.py", line 39, in _parse_output
    (delimiter, version) = self._detect_characteristics(lines)
  File "/home/manjaro/anaconda3/lib/python3.9/site-packages/powertop/decoder.py", line 54, in _detect_characteristics
    assert version.startswith('v')
AssertionError

**Comment by progval** [comment]
I haven't touched this project in years. PowerTOP probably changed its output format since, feel free to send a PR to fix it
